# Examples/Data/IFAC26_2D_RA_runner.py
#
# USER:
#   --mode rt   : VI_mode='rt',   pol_mode='rt',   Δ_VI=δ_rt, Δ_pol=δ_rt
#   --mode apos : VI_mode='apos', pol_mode='apos', Δ_VI=0,    Δ_pol=δ_apos_pol
#                then apply a-posteriori correction with δ_corr to tv before averaging region
#                choose output type with --apos-kind dc|mtl
#
# OUTPUT (same folder as this runner):
#   rt                -> IFAC26_2D_RA_RT.py        (mean_rt_curve)
#   apos --apos-kind dc  -> IFAC26_2D_RA_AposDC.py    (mean_apos_corr_curve)
#   apos --apos-kind mtl -> IFAC26_2D_RA_AposMTL.py   (mean_apos_corr_curve_mtl)

import argparse
from pathlib import Path

import numpy as np
import polytope as pc

from src.models.linmodel import LinModel
from src.models.mdpmodel import MDPModel
from src.specifications.translate import translate
from src.specifications.utils.dfa_tool import dfa_manipulation
from src.abstraction.utils.labeling import dim_label_eps
from src.dynprog.dfa_tree_r1 import DFATree
from src.dynprog.utils.treebasedV import compute_tv_from_tree
from src.dynprog.utils.v_apos import apply_delta_correction_apos
from src.config.delta_ui import parse_delta_list as parse_list


# ---------------- utilities ----------------
def region_mean(tv: np.ndarray, r0: int, r1_incl: int, c0: int, c1_incl: int) -> float:
    """Mean over tv[r0:r1_incl, c0:c1_incl] (safe-clipped)."""
    if tv.ndim != 2:
        raise ValueError(f"Expected 2D tv; got shape {tv.shape}")
    nrows, ncols = tv.shape
    rr0 = max(0, min(nrows - 1, r0))
    rr1 = max(0, min(nrows - 1, r1_incl))
    cc0 = max(0, min(ncols - 1, c0))
    cc1 = max(0, min(ncols - 1, c1_incl))
    if rr1 < rr0 or cc1 < cc0:
        return 0.0
    return float(np.mean(tv[rr0:rr1 + 1, cc0:cc1 + 1]))


def make_delta_vectors_from_scalars(scalars, sysAbs) -> list:
    """Per-dim scalars -> per-state vectors (length N_d)."""
    out = []
    for k in sorted(sysAbs.keys()):
        out.append(np.full(sysAbs[k].N, float(scalars[sorted(sysAbs.keys()).index(k)]), dtype=float))
    return out


def save_curve_as_py(py_path: Path, var_name: str, Ts, curve, meta: dict) -> None:
    """Write a simple Python module with Ts + curve + meta."""
    Ts_list = np.asarray(Ts, dtype=int).tolist()
    curve_list = np.asarray(curve, dtype=float).tolist()

    lines = []
    lines.append("# Auto-generated by IFAC26_2D_RA_runner.py\n")
    lines.append("Ts = " + repr(Ts_list) + "\n")
    lines.append(f"{var_name} = " + repr(curve_list) + "\n")
    lines.append("meta = " + repr(meta) + "\n")

    py_path.write_text("".join(lines), encoding="utf-8")


def out_dir_here() -> Path:
    """Output goes to the same folder as the runner."""
    return Path(__file__).resolve().parent


# ---------------- system + spec ----------------
def build_system_and_spec(sigma_vals):
    """
    2D system built as two 1D subsystems:
      x^+ = 0.9 x + 0.5 u + 0.5 w
    """
    A = {0: np.array([[0.9]]), 1: np.array([[0.9]])}
    B = {0: np.array([[0.5]]), 1: np.array([[0.5]])}
    C = {0: np.array([[1.0]]), 1: np.array([[1.0]])}
    Dm = {0: np.array([[0.0]]), 1: np.array([[0.0]])}
    Bw = {0: np.array([[0.5]]), 1: np.array([[0.5]])}
    mu = {0: np.array([0.0]), 1: np.array([0.0])}
    sigma = {
        0: float(sigma_vals[0]) * np.eye(1),
        1: float(sigma_vals[1]) * np.eye(1),
    }

    sysLTI = {
        0: LinModel(A[0], B[0], C[0], Dm[0], Bw[0], mu=mu[0], sigma=sigma[0]),
        1: LinModel(A[1], B[1], C[1], Dm[1], Bw[1], mu=mu[1], sigma=sigma[1]),
    }

    # DFA: ( (!p2 | !p3) U p1 )
    DFA = translate('( (!p2 | !p3 ) U p1)')
    DFA, letters = dfa_manipulation(
        DFA,
        index_base=0,
        ensure_transitions=True,
        remove_qf_self_loop=True,
        replacements={"!p1 & !p2": "p3&!p1&!p2", "!p1 & !p3": "!p3&!p1"},
        desired_order=['p1', 'p3&!p1&!p2', '!p3&!p1'],
        verbose=False,
    )

    # AP geometry
    s = np.array([[1], [-1]])
    bx = np.array([5, 20])
    bu = np.array([5, 5])
    bp1 = np.array([5, 0])      # p1: [0, 5]
    bp2 = np.array([0, 5])      # p2: [-5, 0]
    bp3 = np.array([-15, 20])   # p3: [-20, -15]
    P1 = pc.Polytope(s, bp1)
    P2 = pc.Polytope(s, bp2)
    P3 = pc.Polytope(s, bp3)

    for i in [0, 1]:
        sysLTI[i].X = pc.Polytope(s, bx)
        sysLTI[i].U = pc.Polytope(s, bu)

    sysLTI[0].regions = [P1, P2]
    sysLTI[1].regions = [P3]
    sysLTI[0].AP = ['p1', 'p2']
    sysLTI[1].AP = ['p3']

    return sysLTI, DFA, letters


def build_abs_and_label(sysLTI, letters, nx_val: int, nu_val: int, eps_val: float):
    sysAbs = {
        0: MDPModel.from_system(
            sysLTI[0],
            nx=nx_val,
            nu=nu_val,
            placement='centers',
            u_placement='endpoints',
            tol=1e-19,
            contract_sum=None,
            compute_P='1d',
        ),
        1: MDPModel.from_system(
            sysLTI[1],
            nx=nx_val,
            nu=nu_val,
            placement='centers',
            u_placement='endpoints',
            tol=1e-19,
            contract_sum=None,
            compute_P='1d',
        ),
    }

    L = dim_label_eps(
        sysAbs,
        sysLTI,
        letters,
        eps=eps_val,
        visualize=False,
        outdir=None,
        prefix="L_eps",
    )
    return sysAbs, L


# ---------------- main ----------------
def main() -> int:
    ap = argparse.ArgumentParser(description="IFAC26 2D RA runner (rt or apos; supports DC/MTL).")

    # === easy mode switch ===
    ap.add_argument("--mode", choices=["rt", "apos"], default="apos",
                    help="rt: robust-tree; apos: a-posteriori (with correction)")
    ap.add_argument("--apos-kind", choices=["dc", "mtl"], default="dc",
                    help="Only used when --mode apos. dc -> AposDC.py, mtl -> AposMTL.py")

    ap.add_argument("--nx", type=int, default=1000)
    ap.add_argument("--nu", type=int, default=10)
    ap.add_argument("--Tmax", type=int, default=80)
    ap.add_argument("--sigma", type=str, default="1.0", help="single or 2-CSV")
    ap.add_argument("--eps", type=float, default=0.1)
    ap.add_argument("--prune-tol", type=float, default=1e-15)
    ap.add_argument("--rows", type=str, default="0,799")
    ap.add_argument("--cols", type=str, default="600,699")

    # deltas
    ap.add_argument("--delta-rt", type=str, default="0.002", help="single or 2-CSV (rt mode)")
    ap.add_argument("--delta-apos-pol", type=str, default="0.002", help="single or 2-CSV (apos mode, policy)")
    ap.add_argument("--delta-corr", type=str, default="0.002", help="single or 2-CSV (apos mode, correction)")

    args = ap.parse_args()

    r0, r1 = [int(x.strip()) for x in args.rows.split(",")]
    c0, c1 = [int(x.strip()) for x in args.cols.split(",")]

    sigma_vals = parse_list(args.sigma, 2, default=1.0)

    sysLTI, DFA, letters = build_system_and_spec(sigma_vals)
    sysAbs, L = build_abs_and_label(sysLTI, letters, args.nx, args.nu, eps_val=args.eps)

    dims = sorted(sysAbs.keys())
    nx_list = [sysAbs[d].N for d in dims]
    nu_list = [sysAbs[d].M for d in dims]
    L_list = [L[d] for d in dims]
    nQ = len(DFA.S)

    # uniform policy + rho
    pol = [[np.full((nx_list[d], nu_list[d]), 1.0 / nu_list[d], dtype=float)
            for d in range(len(dims))]
           for _ in range(nQ)]
    rho = [np.full(nx_list[d], 1.0 / nx_list[d], dtype=float) for d in range(len(dims))]

    # -------- mode-specific setup --------
    corr_delta = None
    if args.mode == "rt":
        delta_rt = parse_list(args.delta_rt, 2, default=0.002)
        delta_VI_vecs = make_delta_vectors_from_scalars(delta_rt, sysAbs)
        delta_pol_vecs = make_delta_vectors_from_scalars(delta_rt, sysAbs)
        VI_mode, pol_mode = "rt", "rt"
        out_file = "IFAC26_2D_RA_RT.py"
        out_var = "mean_rt_curve"
        meta_delta = {"delta_rt": [float(x) for x in delta_rt]}
    else:
        delta_apos_pol = parse_list(args.delta_apos_pol, 2, default=0.002)
        delta_corr = parse_list(args.delta_corr, 2, default=0.002)

        # Δ_VI=0 in apos mode
        delta_VI_vecs = [np.zeros(sysAbs[d].N, dtype=float) for d in dims]
        delta_pol_vecs = make_delta_vectors_from_scalars(delta_apos_pol, sysAbs)
        VI_mode, pol_mode = "apos", "apos"
        corr_delta = delta_corr

        if args.apos_kind == "dc":
            out_file = "IFAC26_2D_RA_AposDC.py"
            out_var = "mean_apos_corr_curve"
        else:  # mtl
            out_file = "IFAC26_2D_RA_AposMTL.py"
            out_var = "mean_apos_corr_curve_mtl"

        meta_delta = {
            "apos_kind": args.apos_kind,
            "delta_apos_pol": [float(x) for x in delta_apos_pol],
            "delta_corr": [float(x) for x in delta_corr],
        }

    # build tree
    G = DFATree(
        DFA, sysAbs, pol, nx_list, L_list,
        delta_VI=delta_VI_vecs,
        delta_pol=delta_pol_vecs,
        pol_mode=pol_mode,
        VI_mode=VI_mode,
    )
    G.initiate()

    Ts = list(range(args.Tmax + 1))
    curve = []

    # t=0
    tv, _ = compute_tv_from_tree(G, DFA, L)
    if args.mode == "apos":
        tv = apply_delta_correction_apos(tv, G, DFA, L, sysAbs, delta_sys=corr_delta, T=0)
    curve.append(region_mean(tv, r0, r1, c0, c1))
    print(f"T=0: mean({args.mode})={curve[-1]:.6g}")

    # t=1..Tmax
    for t in range(1, args.Tmax + 1):
        print(f"=== Iteration {t}/{args.Tmax} (mode={args.mode}) ===")
        if args.mode == "apos":
            G.set_iter(t)

        G.maxpolicy(rho)
        G.update_tree()
        G.prune(args.prune_tol, "leafs")
        G.grow()

        tv, _ = compute_tv_from_tree(G, DFA, L)
        if args.mode == "apos":
            tv = apply_delta_correction_apos(tv, G, DFA, L, sysAbs, delta_sys=corr_delta, T=t + 1)

        curve.append(region_mean(tv, r0, r1, c0, c1))
        print(f"T={t}: mean({args.mode})={curve[-1]:.6g}")

    meta = {
        "mode": args.mode,
        "rows": [r0, r1],
        "cols": [c0, c1],
        "sigma": [float(x) for x in sigma_vals],
        "nx": int(args.nx),
        "nu": int(args.nu),
        "eps": float(args.eps),
        "prune_tol": float(args.prune_tol),
        **meta_delta,
    }

    out_path = out_dir_here() / out_file
    save_curve_as_py(out_path, out_var, Ts, curve, meta)

    print(f"\nSaved: {out_path}")
    print(f"Variable: {out_var}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())